version: "3"

services:
  db:
    platform: linux/x86_64
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: findStudio
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      # MYSQL_USER: user #optional
      # MYSQL_PASSWORD: P@ssw0rd #optional
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes" #optional
      # MYSQL_RANDOM_ROOT_PASSWORD: "yes" #optional
      # MYSQL_ONETIME_PASSWORD: "yes" #optional (MySQL 5.6 or above)
      # MYSQL_INITDB_SKIP_TZINFO: "" #optional
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password

  front:
    depends_on:
      - db
    build:
      context: app
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd app && yarn run dev"
    ports:
      - "4001:3000"

  files:
    build:
      context: files
      dockerfile: Dockerfile
    container_name: files
    volumes:
      - ./:/usr/src/files
    command: sh -c "cd files && yarn run dev"
    ports:
      - "5000:5000"
      