import type { GetServerSidePropsContext, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { Dao } from "../dao";
import { toObject } from "../db";
import { Studio } from "../entities/studio";
import styles from "../styles/Home.module.css";

interface StationSearcherProp {
  stationPicker(station: StationLines): void;
}
const StationSearcher = ({ stationPicker }: StationSearcherProp) => {
  const [results, setResults] = useState<StationLines[]>([]);
  const [composing, setComposing] = useState(false);

  const keyInput = async (value: string) => {
    if (value.length < 2 || composing) setResults([]);
    else search(value);
  };

  const search = async (value: string) => {
    const res = (await fetch(`/api/stations?name=${value}`).then((res) => res.ok && res.json())) as StationLines[];
    res.sort((a, b) => a.stationName.length - b.stationName.length);
    console.log(res);
    setResults(res);
  };

  const compositionEnd = (value: string) => {
    setComposing(false);
    value.length > 1 && search(value);
  };
  return (
    <>
      <input
        onCompositionStart={() => setComposing(true)}
        onCompositionEnd={(e) => compositionEnd(e.currentTarget.value)}
        onInput={(e) => keyInput(e.currentTarget.value)}
      ></input>
      {results?.length > 0 && (
        <div className="resultBox flex-col">
          {results.map((res: StationLines, index) => (
            <div className="station flex-col" key={index} onClick={() => stationPicker(res)}>
              <span className="line">
                {res.lines[0].lineName}
                {res.lines.length > 1 ? <span className="badge">{res.lines.length}</span> : ""}
              </span>
              {res.stationName}
            </div>
          ))}
        </div>
      )}
    </>
  );
};

const Station = () => {
  const [pickedStation, setPickedStation] = useState<StationLines | null>(null);

  return (
    <div id="stationSearcher" className="flex-col">
      <label>駅名</label>
      {pickedStation ? (
        <div onClick={() => setPickedStation(null)}>{pickedStation.stationName}</div>
      ) : (
        <StationSearcher stationPicker={setPickedStation} />
      )}
    </div>
  );
};

const Searcher = () => {
  const [isNormalSearchMode, setIsNormalSearchMode] = useState(true);
  return (
    <div id="searcher">
      <div className="tabs">
        <label data-is-active={isNormalSearchMode} htmlFor="normalSeach">
          駅名を中心に検索
        </label>
        <label data-is-active={!isNormalSearchMode} htmlFor="userSeach">
          利用者条件で検索
        </label>
      </div>
      <div className="body">
        <input id="normalSeach" className={`hide`} type="radio" name="searchType" onChange={() => setIsNormalSearchMode(true)} />
        <input id="userSeach" className={`hide`} type="radio" name="searchType" onChange={() => setIsNormalSearchMode(false)} />
        {isNormalSearchMode ? (
          <div className={"normal"}>
            <Station />
          </div>
        ) : (
          <div className="user">利用者で</div>
        )}
      </div>
    </div>
  );
};

const NewestStudio = () => {
  return;
};

interface Props {
  newStudios: Studio[];
}

const NewStudios = ({ newStudios }: Props) => (
  <div>
    <h1>新着スタジオ</h1>
    {newStudios.map((studio) => (
      <div key={studio.id}>{studio.name}</div>
    ))}
  </div>
);

const Home = ({ newStudios }: Props) => {
  return (
    <div id="container">
      <Head>
        <title>リハスタナビ｜バンドマンのためのリハサールスタジオ情報サイト</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Searcher />
        <NewStudios newStudios={newStudios} />
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const newStudios = await Dao.Studio.getNewestStudio().then(toObject);
  return {
    props: { newStudios }, // will be passed to the page component as props
  };
}
